// Code generated by Thrift Compiler (0.14.2). DO NOT EDIT.

package parquet

import (
	"bytes"
	"context"
	"fmt"
	"time"

	"github.com/apache/thrift/lib/go/thrift"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = timestamppb.Now()
var _ = bytes.Equal

func init() {
}
