// Code generated by Thrift Compiler (0.14.2). DO NOT EDIT.

package parquet

import (
	"bytes"
	"context"
	"fmt"
	"time"

	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var (
	_ = thrift.ZERO
	_ = fmt.Printf
	_ = context.Background
	_ = time.Now
	_ = bytes.Equal
)

func init() {
}
